# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7fa59bcb875aeb0c30126d7a7dfadef8013d84ed341607bd7ef3435d8c4f247b14dd91a5ae90546edff2560865178d4d4cb6116e68b4b8d05717f61711319da

test:
  secret_key_base: 701bc202e3a069a1f29a17097e59049820041d0724032cf9705c6031b045ffb1e9884411341d7be825f16f1876ea76733ac6b981e6da6640457a2d9e29c93efd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
